name: MagicAssistant
author: legobuilder0813
version: 1.0
description: Assists Admins Automagically
main: com.legobuilder0813.MagicAssistant.MagicAssistant
commands:
   gwts:
      description: Glow With The Show!
      permission: magicassistant.gwts
      permission-message: §4Only Cast Members can use this command!
   magicassistant:
      description: Describes the plugin.
      permission: magicassistant.magicassistant
      permission-message: §4Only Cast Members can use this command!
   save:
      description: Saves all the worlds
      permissions: magicassistant.save
      permission-message: §4Only Cast Members can use this command!
   head:
      description: Gives the player a head of another player.
      permission: magicassistant.head
      permission-message: §4Only Cast Members can use this command!
   tp:
      description: Default teleport command
      permission: mcmagic.tp
      permission-message: §4Only Cast Members can use this command!
   day:
      description: Set time to day
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!
   night:
      description: Set time to night
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!
   noon:
      description: Set time to noon
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!