name: MagicAssistant
author: legobuilder0813
version: 1.0
description: Yay MCMagic plugin
main: us.mcmagic.magicassistant.MagicAssistant
commands:
   gwts:
      description: Glow With The Show!
      permission: magicassistant.gwts
      permission-message: §4Only Cast Members can use this command!
   magicassistant:
      description: Describes the plugin.
      permission: magicassistant.magicassistant
      permission-message: §4Only Cast Members can use this command!
   save:
      description: Saves all the worlds
      permissions: magicassistant.save
      permission-message: §4Only Cast Members can use this command!
   tp:
      description: Default teleport command
      permission: mcmagic.tp
      permission-message: §4Only Cast Members can use this command!
   day:
      description: Set time to day
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!
   night:
      description: Set time to night
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!
   noon:
      description: Set time to noon
      permission: mcmagic.time.set
      permission-message: §4Only Cast Members can use this command!
   warp:
      description: Warp Command
      permission: mcmagic.warp
      permission-message: §4Only Staff Members can use this command!
   wrl:
      description: Warp Command
      permission: mcmagic.warp.reload
      permission-message: §4Only Staff Members can use this command!
   setwarp:
      description: Warp Command
      permission: mcmagic.warp.set
      permission-message: §4Only Staff Members can use this command!
   delwarp:
      description: Warp Command
      permission: mcmagic.warp.delete
      permission-message: §4Only Staff Members can use this command!
   uwarp:
      description: Warp Command
      permission: mcmagic.warp.update
      permission-message: §4Only Staff Members can use this command!
   vanish:
      description: Hides you from the Guests!
      permission: vanish.standard
      permission-message: §4You don’t have permission for this command
   v:
      description: Hides you from the Guests!
      permission: vanish.standard
      permission-message: §4You don’t have permission for this command
   joinarcade:
      description: Sends you to the MCMagic Arcade
      permission: mcmagic.joinarcade
      permission-message: §4You don’t have permission for this command
   hub:
      description: This brings the player to the hub.
      permission: mcmagic.hub
      permission-message: §4Please notify a Cast Member that you can’t do this.
   sethub:
      description: Set’s the hub location.
      permissions: hub.set
      permission-message: §4Only Staff Members can use this command!
   delay:
      description: Resets rides automagically!
      permission: mcmagic.delay
      permission-message: §4Only Staff Members can use this command!
   spawn:
      description: Go to our spawn!
      permission: mcmagic.spawn
      permission-message: §4Only Staff Members can use this command!
   setspawn:
      description: Go to our spawn!
      permission: mcmagic.spawn.set
      permission-message: §4Only Staff Members can use this command!
   fly:
      description: Toggle your fly!
      permission: mcmagic.fly
      permission-message: §4Only Staff Members can use this command!
   mb:
      description: Default MagicBand Command!
      permission: band.mb
      permission-message: §4Only Staff Members can use this command!
   more:
      description: Get more of an item!
      permission: mcmagic.more
      permission-message: §4Only Staff Members can use this command!
   ptime:
      description: Change a player's time!
      permission: mcmagic.ptime
      permission-message: §4Only Staff Members can use this command!
   pweather:
      description: Change a player's weather!
      permission: mcmagic.pweather
      permission-message: §4Only Staff Members can use this command!
   heal:
      description: Heal yourself or another player!
      permission: mcmagic.heal
      permission-message: §4Only Staff Members can use this command!
   give:
      description: Give yourself an item!
      permission: mcmagic.give
      permission-message: §4Only Staff Members can use this command!
      aliases: [item, i]
   enderchest:
      description: View a player's Enderchest!
      permission: mcmagic.enderchest
      permission-message: §4Only Staff Members can use this command!
   invsee:
      description: View a player's Inventory!
      permission: mcmagic.invsee
      permission-message: §4Only Staff Members can use this command!
   smite:
      description: Strike a lightning bolt!
      permission: mcmagic.smite
      permission-message: §4Only Staff Members can use this command!
   head:
      description: Get a certain player's head!
      permission: mcmagic.head
      permission-message: §4Only Staff Members can use this command!
   joinarcade:
      description: Change a player's time!
      permission: mcmagic.joinarcade
      permission-message: §4Only Staff Members can use this command!
   helpop:
      description: Change a player's time!
      permission: mcmagic.joinarcade
      permission-message: §4Only Staff Members can use this command!
      aliases: ac
   invcheck:
      description: This clears all banned items!
      permission: mcmagic.invcheck
      permission-message: §4Only Cast Members can use this command!
   bc:
      description: Broadcast a message!
      permission: mcmagic.bc
      permission-message: §4Only Cast Members can use this command!